### ISSUE TITLE
为什么就不能一个golang 程序启动结束呢，还要docker依赖一堆

### ISSUE THREAD

**Issue by shangguanbucai** [mojocn/rdpgo#4]
有没有可能把容器涉及到的协议，集成到golang 代码里，这样go 一键即可运行了啊。。

**Comment by mojocn** [comment]
> 

docker-composer 里面的除了 guacomole guacd 是必须的 其他的 都是demo的虚拟机(演示用的啊)

没有那么多的服务器和开启rdp协议的 windows桌面电脑

**Comment by shangguanbucai** [comment]
最好是一个容器都不要，直接一个go 程序搞定。

**Comment by shangguanbucai** [comment]
还要安装docker 啥的，体验性差。
