### ISSUE TITLE
RDP 连接出现蓝黑背景间歇闪屏或黑屏许久才进入桌面

### ISSUE THREAD

**Issue by rysinal** [mojocn/rdpgo#6]

**Comment by shangguanbucai** [comment]
我就没出现过远程桌面

rysinal ***@***.***>于2022年7月15日 周五上午11:27写道：

**Comment by rysinal** [comment]
闪屏问题找到了 鼠标插件问题，换官方的写法就OK了 ref https://guacamole.apache.org/doc/guacamole-common-js/Guacamole.Mouse.html
